### ISSUE TITLE
Plugin causes less mixin syntax compilation error 插件导致 less mixin 语法编译报错

### ISSUE THREAD

**Issue by hughfenghen** [mzohaibqc/antd-theme-webpack-plugin#23]
```less
.a,
#b {
  color: red;
}

.mixin-class {
  .a();
}

.mixin-id {
  #b();
}
```
![image](https://user-images.githubusercontent.com/3307051/54257413-2df7b780-459a-11e9-8f4e-3a7507be7ad8.png)

相关issue：https://github.com/ant-design/ant-design-pro/issues/3335
