### ISSUE TITLE
Can not use the @menu-dark-arrow-color theme variable 

### ISSUE THREAD

**Issue by romangutkin** [mzohaibqc/antd-theme-webpack-plugin#25]
When i add the @menu-dark-arrow-color variable to the themeVariables array i get an error in the console: "variable @menu-dark-arrow-color0f6 is undefined".
```js
// webpack.config.js
themeVariables: [
    '@primary-color',
    '@text-color',
    '@success-color',
    '@warning-color',
    '@error-color',
    '@font-size-base',
    '@heading-color',
    '@text-color-secondary',
    '@disabled-color',
    '@border-radius-base',
    '@border-color-base',
    '@box-shadow-base',
    '@layout-trigger-background',
    '@layout-sider-background',
    '@menu-dark-bg',
    '@menu-dark-color',
    '@menu-dark-arrow-color' // Everything works but this one
  ],
```

I have looked in the color.less file where the error happened and saw:
```css
/* color.less */
.ant-tag-pink {
  color: #eb2f96;
  background: @menu-dark-arrow-color0f6;
  border-color: #ffadd2;
}
```
I don't understand why but i think that when the colors.less file is evaluated the variable has not yet been defined.
