### ISSUE TITLE
can't change @primary-color at other less file

### ISSUE THREAD

**Issue by guaijie** [mzohaibqc/antd-theme-webpack-plugin#34]
## 1.  In `varFile` (variables.less):
```less
@import "../../node_modules/antd/lib/style/themes/default.less";
@primary-color: red;
```
## 2. Then i modify it:
```js
window.less.modifyVars({ "@primary-color": "green" )}
```
## 3. use `@primary-color` at other less file
```html
<div className="modified" />
```
```less
.modified {
    background-color: @primary-color
}
``` 
> result: @primary-color is undefined;
```less
@import "./variables.less";
.modified {
    background-color: @primary-color
}
```
> result: i can`t change `.modified' class color
